version: '3.7'

services:
  camunda:
    image: camunda/camunda-bpm-platform:run-latest
    container_name: camunda
    ports:
      - "8083:8080"
    environment:
      - DB_DRIVER=com.mysql.cj.jdbc.Driver
      - DB_URL=jdbc:mysql://host.docker.internal:3306/demo_db?autoReconnect=true
      - DB_USERNAME=root
      - DB_PASSWORD=Bahman2462
      - CAMUNDA_BPM_RUN_EXAMPLE_ENABLED=false
    networks:
      - camunda-net

networks:
  camunda-net: